CREATE TABLE  "CAPDETAI" 
   (    "CAPDETAIID" NUMBER(2,0) NOT NULL ENABLE, 
    "TENCAPDETAI" VARCHAR2(255) NOT NULL ENABLE, 
     CONSTRAINT "PK_CAPDETAI" PRIMARY KEY ("CAPDETAIID") ENABLE
   ) ;CREATE TABLE  "ORG_ORGANIZATION" 
   (    "ORG_ID" NUMBER(10,0) NOT NULL ENABLE, 
     CONSTRAINT "PK_ORG" PRIMARY KEY ("ORG_ID") ENABLE
   ) ;CREATE TABLE  "ORG_OFFICER" 
   (    "OFFICER_ID" NUMBER(15,0) NOT NULL ENABLE, 
    "DEPT_ID" NUMBER(10,0) NOT NULL ENABLE, 
    "SUBDEPT_ID" NUMBER(10,0) NOT NULL ENABLE, 
     CONSTRAINT "PK_OFFICERID" PRIMARY KEY ("OFFICER_ID") ENABLE
   ) ;CREATE TABLE  "TRANGTHAI" 
   (    "TRANGTHAIID" NUMBER(3,0) NOT NULL ENABLE, 
    "TENTRANGTHAI" VARCHAR2(255) NOT NULL ENABLE, 
     CONSTRAINT "PK_TENTRANGTHAIID" PRIMARY KEY ("TRANGTHAIID") ENABLE
   ) ;CREATE TABLE  "XEPLOAI" 
   (    "XEPLOAIID" NUMBER(3,0) NOT NULL ENABLE, 
    "TENXEPLOAI" VARCHAR2(255) NOT NULL ENABLE, 
     CONSTRAINT "PK_XEPLOAIID" PRIMARY KEY ("XEPLOAIID") ENABLE
   ) ;CREATE TABLE  "DETAI" 
   (    "DETAIID" NUMBER(6,0) NOT NULL ENABLE, 
    "MADETAI" VARCHAR2(30) NOT NULL ENABLE, 
    "TENDETAI" VARCHAR2(255) NOT NULL ENABLE, 
    "MUCTIEU" VARCHAR2(255) NOT NULL ENABLE, 
    "NGAYBD_DUKIEN" DATE NOT NULL ENABLE, 
    "NGAYKT_DUKIEN" DATE NOT NULL ENABLE, 
    "KINHPHI_DUKIEN" NUMBER(19,2) NOT NULL ENABLE, 
    "CAPDETAIID" NUMBER(2,0) NOT NULL ENABLE, 
    "CHUNHIEMDETAI" NUMBER(15,0) NOT NULL ENABLE, 
    "NOIDUNGTONGQUAN" CLOB, 
    "TRANGTHAIID" NUMBER(3,0) NOT NULL ENABLE, 
    "KINHPHI_HOANTHANH" NUMBER(19,2), 
    "XEPLOAIID" NUMBER(3,0), 
    "TONGDIEM" NUMBER(5,2), 
    "FILEATTACHID" NUMBER(10,0), 
     CONSTRAINT "PK_DETAIID" PRIMARY KEY ("DETAIID") ENABLE
   ) ;CREATE TABLE  "DANHGIA" 
   (    "DANHGIAID" NUMBER(10,0) NOT NULL ENABLE, 
    "LOAIDANHGIA" NUMBER(2,0) NOT NULL ENABLE, 
    "DIEMDANHGIA" NUMBER(2,0) NOT NULL ENABLE, 
    "DETAIID" NUMBER(6,0) NOT NULL ENABLE, 
     CONSTRAINT "PK_DANHGIAID" PRIMARY KEY ("DANHGIAID") ENABLE
   ) ;CREATE TABLE  "DEMO_CUSTOMERS" 
   (    "CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
    "CUST_FIRST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "CUST_LAST_NAME" VARCHAR2(20) NOT NULL ENABLE, 
    "CUST_STREET_ADDRESS1" VARCHAR2(60), 
    "CUST_STREET_ADDRESS2" VARCHAR2(60), 
    "CUST_CITY" VARCHAR2(30), 
    "CUST_STATE" VARCHAR2(2), 
    "CUST_POSTAL_CODE" VARCHAR2(10), 
    "PHONE_NUMBER1" VARCHAR2(25), 
    "PHONE_NUMBER2" VARCHAR2(25), 
    "CREDIT_LIMIT" NUMBER(9,2), 
    "CUST_EMAIL" VARCHAR2(30), 
     CONSTRAINT "DEMO_CUST_CREDIT_LIMIT_MAX" CHECK (credit_limit <= 5000) ENABLE, 
     CONSTRAINT "DEMO_CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID") ENABLE
   ) ;CREATE TABLE  "DEMO_USERS" 
   (    "USER_ID" NUMBER, 
    "USER_NAME" VARCHAR2(100), 
    "PASSWORD" VARCHAR2(4000), 
    "CREATED_ON" DATE, 
    "QUOTA" NUMBER, 
    "PRODUCTS" CHAR(1), 
    "EXPIRES_ON" DATE, 
    "ADMIN_USER" CHAR(1), 
     CONSTRAINT "DEMO_USERS_PK" PRIMARY KEY ("USER_ID") ENABLE
   ) ;CREATE TABLE  "DEMO_ORDERS" 
   (    "ORDER_ID" NUMBER NOT NULL ENABLE, 
    "CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
    "ORDER_TOTAL" NUMBER(8,2), 
    "ORDER_TIMESTAMP" DATE, 
    "USER_ID" NUMBER, 
     CONSTRAINT "DEMO_ORDER_TOTAL_MIN" CHECK (order_total >= 0) ENABLE, 
     CONSTRAINT "DEMO_ORDER_PK" PRIMARY KEY ("ORDER_ID") ENABLE
   ) ;CREATE TABLE  "DEMO_PRODUCT_INFO" 
   (    "PRODUCT_ID" NUMBER NOT NULL ENABLE, 
    "PRODUCT_NAME" VARCHAR2(50), 
    "PRODUCT_DESCRIPTION" VARCHAR2(2000), 
    "CATEGORY" VARCHAR2(30), 
    "PRODUCT_AVAIL" VARCHAR2(1), 
    "LIST_PRICE" NUMBER(8,2), 
    "PRODUCT_IMAGE" BLOB, 
    "MIMETYPE" VARCHAR2(255), 
    "FILENAME" VARCHAR2(400), 
    "IMAGE_LAST_UPDATE" DATE, 
     CONSTRAINT "DEMO_PRODUCT_INFO_PK" PRIMARY KEY ("PRODUCT_ID") ENABLE
   ) ;CREATE TABLE  "DEMO_ORDER_ITEMS" 
   (    "ORDER_ITEM_ID" NUMBER(3,0) NOT NULL ENABLE, 
    "ORDER_ID" NUMBER NOT NULL ENABLE, 
    "PRODUCT_ID" NUMBER NOT NULL ENABLE, 
    "UNIT_PRICE" NUMBER(8,2) NOT NULL ENABLE, 
    "QUANTITY" NUMBER(8,0) NOT NULL ENABLE, 
     CONSTRAINT "DEMO_ORDER_ITEMS_PK" PRIMARY KEY ("ORDER_ITEM_ID") ENABLE
   ) ;CREATE TABLE  "DEMO_STATES" 
   (    "ST" VARCHAR2(30), 
    "STATE_NAME" VARCHAR2(30)
   ) ;CREATE TABLE  "DEPT" 
   (    "DEPTNO" NUMBER(2,0), 
    "DNAME" VARCHAR2(14), 
    "LOC" VARCHAR2(13), 
     PRIMARY KEY ("DEPTNO") ENABLE
   ) ;CREATE TABLE  "DUTOAN" 
   (    "DUTOANID" NUMBER(10,0) NOT NULL ENABLE, 
    "LOAIDUTOAN" NUMBER(2,0) NOT NULL ENABLE, 
    "DUTOAN" NUMBER(19,2) NOT NULL ENABLE, 
    "DETAIID" NUMBER(6,0) NOT NULL ENABLE, 
     CONSTRAINT "PK_DUTOANID" PRIMARY KEY ("DUTOANID") ENABLE
   ) ;CREATE TABLE  "EMP" 
   (    "EMPNO" NUMBER(4,0) NOT NULL ENABLE, 
    "ENAME" VARCHAR2(10), 
    "JOB" VARCHAR2(9), 
    "MGR" NUMBER(4,0), 
    "HIREDATE" DATE, 
    "SAL" NUMBER(7,2), 
    "COMM" NUMBER(7,2), 
    "DEPTNO" NUMBER(2,0), 
     PRIMARY KEY ("EMPNO") ENABLE
   ) ;CREATE TABLE  "TIENDO" 
   (    "TIENDOID" NUMBER(10,0) NOT NULL ENABLE, 
    "TIENDOHOANTHANH" NUMBER(3,0) NOT NULL ENABLE, 
    "MOTA" VARCHAR2(255) NOT NULL ENABLE, 
    "NGAYCAPNHAT" DATE NOT NULL ENABLE, 
    "FILEATTACHID" NUMBER(10,0), 
    "DETAIID" NUMBER(6,0) NOT NULL ENABLE, 
     CONSTRAINT "PK_TIENDOID" PRIMARY KEY ("TIENDOID") ENABLE
   ) ;CREATE TABLE  "FILE_ATTACH" 
   (    "FILEID" NUMBER(10,0) NOT NULL ENABLE, 
    "DETAIID" NUMBER(6,0) NOT NULL ENABLE, 
    "MOTA" VARCHAR2(255) NOT NULL ENABLE, 
    "NOIDUNG" BLOB, 
    "NGUOI_CN" NUMBER(15,0) NOT NULL ENABLE, 
    "NGAY_CN" DATE NOT NULL ENABLE, 
    "TIENDOID" NUMBER(10,0) NOT NULL ENABLE, 
     CONSTRAINT "PK_FILEID" PRIMARY KEY ("FILEID") ENABLE
   ) ;CREATE TABLE  "NHANSUTHAMGIA" 
   (    "DETAIID" NUMBER(6,0) NOT NULL ENABLE, 
    "OFFICER_ID" NUMBER(15,0) NOT NULL ENABLE, 
     CONSTRAINT "PK_NHANSU" PRIMARY KEY ("DETAIID", "OFFICER_ID") ENABLE
   ) ;ALTER TABLE  "DEMO_ORDERS" ADD CONSTRAINT "DEMO_ORDERS_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
      REFERENCES  "DEMO_CUSTOMERS" ("CUSTOMER_ID") ENABLE;ALTER TABLE  "DEMO_ORDERS" ADD CONSTRAINT "DEMO_ORDERS_USER_ID_FK" FOREIGN KEY ("USER_ID")
      REFERENCES  "DEMO_USERS" ("USER_ID") ENABLE;ALTER TABLE  "DEMO_ORDER_ITEMS" ADD CONSTRAINT "DEMO_ORDER_ITEMS_FK" FOREIGN KEY ("ORDER_ID")
      REFERENCES  "DEMO_ORDERS" ("ORDER_ID") ON DELETE CASCADE ENABLE;ALTER TABLE  "DEMO_ORDER_ITEMS" ADD CONSTRAINT "DEMO_ORDER_ITEMS_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
      REFERENCES  "DEMO_PRODUCT_INFO" ("PRODUCT_ID") ON DELETE CASCADE ENABLE;ALTER TABLE  "DETAI" ADD CONSTRAINT "FK_CAPDETAIID" FOREIGN KEY ("CAPDETAIID")
      REFERENCES  "CAPDETAI" ("CAPDETAIID") ENABLE;ALTER TABLE  "DETAI" ADD CONSTRAINT "FK_CHUNHIEMDETAI" FOREIGN KEY ("CHUNHIEMDETAI")
      REFERENCES  "ORG_OFFICER" ("OFFICER_ID") ENABLE;ALTER TABLE  "ORG_OFFICER" ADD CONSTRAINT "FK_DEPTID" FOREIGN KEY ("DEPT_ID")
      REFERENCES  "ORG_ORGANIZATION" ("ORG_ID") ENABLE;ALTER TABLE  "FILE_ATTACH" ADD CONSTRAINT "FK_DETAIFILE" FOREIGN KEY ("DETAIID")
      REFERENCES  "DETAI" ("DETAIID") ENABLE;ALTER TABLE  "DANHGIA" ADD CONSTRAINT "FK_DETAIID" FOREIGN KEY ("DETAIID")
      REFERENCES  "DETAI" ("DETAIID") ENABLE;ALTER TABLE  "NHANSUTHAMGIA" ADD CONSTRAINT "FK_DETAIID1" FOREIGN KEY ("DETAIID")
      REFERENCES  "DETAI" ("DETAIID") ENABLE;ALTER TABLE  "DUTOAN" ADD CONSTRAINT "FK_DETAIIDDUTOAN" FOREIGN KEY ("DETAIID")
      REFERENCES  "DETAI" ("DETAIID") ENABLE;ALTER TABLE  "TIENDO" ADD CONSTRAINT "FK_DETAITIENDO" FOREIGN KEY ("DETAIID")
      REFERENCES  "DETAI" ("DETAIID") ENABLE;ALTER TABLE  "FILE_ATTACH" ADD CONSTRAINT "FK_NGUOICN" FOREIGN KEY ("NGUOI_CN")
      REFERENCES  "ORG_OFFICER" ("OFFICER_ID") ENABLE;ALTER TABLE  "NHANSUTHAMGIA" ADD CONSTRAINT "FK_OFFICERID1" FOREIGN KEY ("OFFICER_ID")
      REFERENCES  "ORG_OFFICER" ("OFFICER_ID") ENABLE;ALTER TABLE  "ORG_OFFICER" ADD CONSTRAINT "FK_SUBDEPTID" FOREIGN KEY ("SUBDEPT_ID")
      REFERENCES  "ORG_ORGANIZATION" ("ORG_ID") ENABLE;ALTER TABLE  "FILE_ATTACH" ADD CONSTRAINT "FK_TIENDOFILE" FOREIGN KEY ("TIENDOID")
      REFERENCES  "TIENDO" ("TIENDOID") ENABLE;ALTER TABLE  "DETAI" ADD CONSTRAINT "FK_TRANGTHAIID" FOREIGN KEY ("TRANGTHAIID")
      REFERENCES  "TRANGTHAI" ("TRANGTHAIID") ENABLE;ALTER TABLE  "DETAI" ADD CONSTRAINT "FK_XEPLOAI" FOREIGN KEY ("XEPLOAIID")
      REFERENCES  "XEPLOAI" ("XEPLOAIID") ENABLE;ALTER TABLE  "EMP" ADD FOREIGN KEY ("MGR")
      REFERENCES  "EMP" ("EMPNO") ENABLE;ALTER TABLE  "EMP" ADD FOREIGN KEY ("DEPTNO")
      REFERENCES  "DEPT" ("DEPTNO") ENABLE;​​